import type { ReactNode } from 'react';

export function DashboardShell({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-surface-muted pb-8">
      {children}
    </div>
  );
}

export function DashboardFooter() {
  return (
    <footer className="py-8 text-center text-xs text-[#bbb]">
      Amber Supplier Satisfaction Survey — Confidential Dashboard &nbsp;|&nbsp; Generated by
      Third-Party Agency &nbsp;|&nbsp; For Internal Use Only
    </footer>
  );
}
